# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependency"
    commit-message:
      prefix: "chore"
      include: "scope"

 # Enable updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Looks for workflows in the .github/workflows directory
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"

  # --- Optional: Uncomment and adjust if you have native Android dependencies ---
  - package-ecosystem: "gradle"
    directory: "/android" # Adjust if your main build.gradle is elsewhere
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-android)"
      include: "scope"
    labels:
      - "dependencies"
      - "android"
      - "native"

  # --- Optional: Uncomment and adjust if you have native iOS dependencies ---
  - package-ecosystem: "cocoapods"
    directory: "/ios" # Adjust if your Podfile is elsewhere
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps-ios)"
      include: "scope"
    labels:
      - "dependencies"
      - "ios"
      - "native"

