name: flutter_boilerplate
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # UI and icons
  cupertino_icons: ^1.0.5
  
  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Dependency injection
  get_it: ^8.0.3
  
  # Navigation
  go_router: ^15.2.0
  
  # Network and API
  dio: ^5.4.1
  logger: ^2.6.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  
  # JSON handling and serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Environment configuration
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.3.0
  
  # Analytics and monitoring
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.7
  sentry_flutter: ^9.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.15
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # Environment files
    - .env
    - .env.dev
    - .env.staging
    - .env.prod
